In [1]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
b = np.array([(2, 5, 7), (1, 2, 3), (2, 3, 4)])
print(b)

[[2 5 7]
 [1 2 3]
 [2 3 4]]


criar matriz de 0 linhas x coluna

In [4]:
c = np.zeros((4, 3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
d = np.ones((4, 3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


matriz quadrada

In [7]:
e = np.eye(5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
print(b.max())
print(b.min())
print(b.std()) # desvio padrão

7 1 1.7497795275581802
